### ISSUE TITLE
非常好的脚本！一点补充：

### ISSUE THREAD

**Issue by wang20150419** [185264646/HUST-login#1]
这个脚本可能是 github 上登录锐捷认证最好（完善）的。

不过有点点小遗憾：
函数 generate_encrypted_password() 的参数设置，可能算个笔误，在低版本  openssl （如：openwrt 15.05 /18.06 系统） 里执行出错。
修改为（ keyform=DER --> keyform DER）：
   encrypted_pass=$(openssl rsautl -encrypt -pubin -keyform DER -inkey "$pem_path" -in "$pass_path" -raw | xxd -ps -c 256)

另外，openwrt 15.05，缺少 jq ，可用系统自带的 jsonfilter 替代（也可用  sed）。
如要在openwrt 15.05里使用，对应的修改：
get_public_key_param() 函数：
       modulus=$(echo "$JSON" | jsonfilter -e '@.publicKeyModulus')
       exponent=$(echo "$JSON" | jsonfilter -e '@.publicKeyExponent')
send_login_request() 函数：
       if [[ $(echo "$RET"| jsonfilter -e '@.result') = 'success' ]]; then
       echo "$RET"| jsonfilter -e '@.message'

补充：如果使用 小米/红米的 路由器原生固件（破解了SSH权限的），缺少 bash 和 xxd，可在这里下载：
bash-static:    https://github.com/robxu9/bash-static
xxd:  https://github.com/andrew-d/static-binaries/tree/master/binaries/linux/arm
（redmi ax6s, ax6000 测试 OK）

**Comment by 185264646** [comment]
> 这个脚本可能是 github 上登录锐捷认证最好（完善）的。
> 
> 不过有点点小遗憾： 函数 generate_encrypted_password() 的参数设置，可能算个笔误，在低版本 openssl （如：openwrt 15.05 /18.06 系统） 里执行出错。 修改为（ keyform=DER --> keyform DER）： encrypted_pass=$(openssl rsautl -encrypt -pubin -keyform DER -inkey "$pem_path" -in "$pass_path" -raw | xxd -ps -c 256)
> 
v2.0中改用openssl-pkeyutl，顺便修复了该问题。
> 另外，openwrt 15.05，缺少 jq ，可用系统自带的 jsonfilter 替代（也可用 sed）。 如要在openwrt 15.05里使用，对应的修改： get_public_key_param() 函数： modulus=$(echo "$JSON" | jsonfilter -e '@.publicKeyModulus') exponent=$(echo "$JSON" | jsonfilter -e '@.publicKeyExponent') send_login_request() 函数： if [[ $(echo "$RET"| jsonfilter -e '@.result') = 'success' ]]; then echo "$RET"| jsonfilter -e '@.message'

jsonfilter是openwrt上专用的工具，其他发行版都没有，可考虑自行将jq backport到旧版本的openwrt。也可在release中下载[静态编译的jq](/jqlang/jq/releases)
> 
> 补充：如果使用 小米/红米的 路由器原生固件（破解了SSH权限的），缺少 bash 和 xxd，可在这里下载： bash-static: https://github.com/robxu9/bash-static xxd: https://github.com/andrew-d/static-binaries/tree/master/binaries/linux/arm （redmi ax6s, ax6000 测试 OK）
