### ISSUE TITLE
新版本中 set -eu 对登录的影响

### ISSUE THREAD

**Issue by wang20150419** [185264646/HUST-login#2]
环境：openwrt-21.02.7
最新的带 set -eu 的版本，
使用 http://192.168.50.3:8080/ 下线后，
运行 login， 无任何提示退出，有时提示 Network is down!，网络无法登录。
如果把 set -eu 注释，则能成功登录。

测试过程输出信息参考：
root@OpenWrt:/etc# ping t.cn
PING t.cn (39.105.18.168): 56 data bytes

--- t.cn ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
root@OpenWrt:/etc# /etc/login2.sh -u 1234567891 -p abcdefg
Network is down!
root@OpenWrt:/etc# /etc/login2.sh -u 1234567891 -p abcdefg
root@OpenWrt:/etc# ping t.cn
PING t.cn (39.105.18.168): 56 data bytes

--- t.cn ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
root@OpenWrt:/etc# vi login2.sh  （注释 set -eu）
root@OpenWrt:/etc# /etc/login2.sh -u 1234567891 -p abcdefg
success

**Comment by 185264646** [comment]
> 环境：openwrt-21.02.7 最新的带 set -eu 的版本， 使用 http://192.168.50.3:8080/ 下线后， 运行 login， 无任何提示退出，有时提示 Network is down!，网络无法登录。 如果把 set -eu 注释，则能成功登录。
> 
已经将该commit回退掉
> 测试过程输出信息参考： root@OpenWrt:/etc# ping t.cn PING t.cn (39.105.18.168): 56 data bytes
> 
> --- t.cn ping statistics --- 3 packets transmitted, 0 packets received, 100% packet loss root@OpenWrt:/etc# /etc/login2.sh -u 1234567891 -p abcdefg Network is down! root@OpenWrt:/etc# /etc/login2.sh -u 1234567891 -p abcdefg root@OpenWrt:/etc# ping t.cn PING t.cn (39.105.18.168): 56 data bytes
> 
> --- t.cn ping statistics --- 4 packets transmitted, 0 packets received, 100% packet loss root@OpenWrt:/etc# vi login2.sh （注释 set -eu） root@OpenWrt:/etc# /etc/login2.sh -u 1234567891 -p abcdefg success

请问能否使用bash -x login.sh -u xxxxx -p xxxxx运行脚本，将出问题时的输出贴在此处，以方便排查?

**Comment by wang20150419** [comment]
set -eu 影响 { redir_url="$(get_cur_network_state)"; ret=$?; } 的返回值，注释后正常 ret=1, 加上则触发 exit_handle，在exit_handle之前，通过对输出的文本对比，两者完全一样（不记 set -eu 这行）。

bash -x login.sh -u xxx -p xxx 输出如下：
+ readonly CURL_TMOUT=3
+ CURL_TMOUT=3
+ username=
+ password=
+ cert_path=
+ padded_pass_path=
+ set -eu
+ trap exit_handler exit
+ parse_args -u xxxxx -p xxxxx
+ local opt
+ getopts u:p: opt
+ case "$opt" in
+ username=xxxxx
+ getopts u:p: opt
+ case "$opt" in
+ password=xxxxx
+ getopts u:p: opt
+ shift 4
+ '[' -z xxxxx ']'
+ '[' -z xxxxx ']'
+ '[' 0 -gt 0 ']'
+ return 0
++ get_cur_network_state
++ local page
++ local url
+++ quiet_curl http://detectportal.firefox.com/
+++ curl -s --connect-timeout 3 http://detectportal.firefox.com/
++ page='<script>top.self.location.href='\''http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...'</script>
++ '[' '<script>top.self.location.href='\''http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...'</script>
+++ parse_page '<script>top.self.location.href='\''http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...'</script>
++++ sed -ne 's/^<script>.*='\''\(.*\)'\''<\/script>/\1/p'
+++ ret='http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...
+++ '[' -z 'http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...
+++ printf %s 'http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...
++ url='http://192.168.50.3:8080/eportal/index.jsp?wlanuserip ...
++ printf %s 'http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...
++ return 1
+ redir_url='http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...
+ exit_handler
+ rm -f '' ''

**Comment by 185264646** [comment]
> set -eu 影响 { redir_url="$(get_cur_network_state)"; ret=$?; } 的返回值，注释后正常 ret=1, 加上则触发 exit_handle，在exit_handle之前，通过对输出的文本对比，两者完全一样（不记 set -eu 这行）。
> 
> bash -x login.sh -u xxx -p xxx 输出如下：
> 
> * readonly CURL_TMOUT=3
> * CURL_TMOUT=3
> * username=
> * password=
> * cert_path=
> * padded_pass_path=
> * set -eu
> * trap exit_handler exit
> * parse_args -u xxxxx -p xxxxx
> * local opt
> * getopts u:p: opt
> * case "$opt" in
> * username=xxxxx
> * getopts u:p: opt
> * case "$opt" in
> * password=xxxxx
> * getopts u:p: opt
> * shift 4
> * '[' -z xxxxx ']'
> * '[' -z xxxxx ']'
> * '[' 0 -gt 0 ']'
> * return 0
>   ++ get_cur_network_state
>   ++ local page
>   ++ local url
>   +++ quiet_curl http://detectportal.firefox.com/
>   +++ curl -s --connect-timeout 3 http://detectportal.firefox.com/
>   ++ page='<script>top.self.location.href='''http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...'</script>
>   ++ '[' '<script>top.self.location.href='''http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...'</script>
>   +++ parse_page '<script>top.self.location.href='''http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...'</script>
>   ++++ sed -ne 's/^<script>._='''(._)'''</script>/\1/p'
>   +++ ret='http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...
>   +++ '[' -z 'http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...
>   +++ printf %s 'http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...
>   ++ url='http://192.168.50.3:8080/eportal/index.jsp?wlanuserip ...
>   ++ printf %s 'http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...
>   ++ return 1
> * redir_url='http://192.168.50.3:8080/eportal/index.jsp?wlanuserip= ...
> * exit_handler
> * rm -f '' ''

感谢测试，最新的修复在hotfix/2分支中。欢迎帮忙测试该分支是否修复该问题。

**Comment by wang20150419** [comment]
测试一切正常，BUG完美修复！
