### ISSUE TITLE
建议修改 网络连通 判定网址

### ISSUE THREAD

**Issue by wang20150419** [185264646/HUST-login#3]
现在的版本，使用 http://detectportal.firefox.com/ 判定网络是否连通。
理论上没问题。但是，因为 detectportal.firefox.com 的 ping 延时有时超过300ms，导致误判。

建议修改为：
苹果：http://captive.apple.com/  （HTML：Success ）
或微软： http://www.msftconnecttest.com/connecttest.txt （纯文本：Microsoft Connect Test）
或谷歌：http://www.google.cn/generate_204  （http状态码：204）
其中，苹果和微软服务器可能位于香港，响应 55ms左右，谷歌服务器位于上海，响应最快。

**Comment by 185264646** [comment]
> 现在的版本，使用 http://detectportal.firefox.com/ 判定网络是否连通。 理论上没问题。但是，因为 detectportal.firefox.com 的 ping 延时有时超过300ms，导致误判。

程序默认超时设置为3秒，误判可能性很低
> 
> 建议修改为： 苹果：http://captive.apple.com/ （HTML：Success ） 或微软： http://www.msftconnecttest.com/connecttest.txt （纯文本：Microsoft Connect Test） 或谷歌：http://www.google.cn/generate_204 （http状态码：204） 其中，苹果和微软服务器可能位于香港，响应 55ms左右，谷歌服务器位于上海，响应最快。
本项目不打算直接使用微软、苹果、谷歌等公司的detect portal服务，原因如下：
1. 微软和谷歌是我国网络监管的重点审查对象，其提供的网络服务在我国境内无法做任何稳定性保障；
1. 随意使用商业公司为自己的软件或设备提供的服务有可能涉及未知法律风险。
1. 本项目是采用GPL协议的开源项目，不打算采用商业公司提供的网络服务。

综上，不考虑采用以上公司提供的captive portal服务。如果用户自己有需求，可自行修改源码。本项目不接受相关issue和pr。如果境内有非盈利组织提供的detect portal服务，在有充足证据表明服务质量高于`detectportal.firefox.com`的情况下，可以考虑采用。
