### ISSUE TITLE
login v2.1 在旧版openssl (v1.0.2) 的问题及其解决方法

### ISSUE THREAD

**Issue by wang20150419** [185264646/HUST-login#5]
最近玩小米AX3600路由器，破解SSH后，使用此登录程序（v2.1）报错，调试信息为：
<pre> 
      ++ openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf -
      Error loading config file '-'
 </pre>

分析发现 ，程序执行到这里(232行)：
       openssl asn1parse -out "$cert" -noout -genconf - <<EOF ||
           ...
       EOF
出错，检查其 openssl, 是 v1.0.2q 版本。但在 v1.1.1版本里，运行是正常的。
查版本历史，对这部分的处理，使用的临时文件，则是正常的。
<pre> 
function get_public_key_pem() {
        openssl asn1parse -genconf $1 -out ${pem_path:=$(mktemp)} >/dev/null
        TMP_FILE="$TMP_FILE $pem_path"
        return 0
}
function generate_asn() {
        head="
            ...
       "
        head="${head}n=INTEGER:0x${modulus}
e=INTEGER:0x${exponent}"
        echo "$head">$1
        return 0
}
function generate_encrypted_password() {
        ASN_PATH=$(mktemp)
        TMP_FILE="$TMP_FILE $ASN_PATH"
        generate_asn "$ASN_PATH"
        get_public_key_pem "$ASN_PATH"
        pass_pad_zero "$1>$macString" 128
        encrypted_pass=$(openssl rsautl -encrypt -pubin -keyform DER -inkey "$pem_path" -in "$pass_path" -raw | xxd -ps -c 256)
        return 0
}
</pre>
参照此历史版本，修改后在 openssl v1.0.2 版本下成功登录。

**Comment by 185264646** [comment]
> 最近玩小米AX3600路由器，破解SSH后，使用此登录程序（v2.1）报错，调试信息为：
> 
>  
>       ++ openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf -
能否尝试一下将这一行修改为`openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf /dev/stdin`之后，能否在旧版本openssl下工作呢？
>       Error loading config file '-'
>  
>

**Comment by wang20150419** [comment]
> > 最近玩小米AX3600路由器，破解SSH后，使用此登录程序（v2.1）报错，调试信息为：
> > ```
> >   ++ openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf -
> > ```
> 
> 能否尝试一下将这一行修改为`openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf /dev/stdin`之后，能否在旧版本openssl下工作呢？
> 
> > ```
> >   Error loading config file '-'
> > ```

这个改动，在 openssl v1.1.1 里就不能成功。出错提示：
<pre>Can't open /dev/stdin for reading, No such file or directory
2011782736:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/dev/stdin','r') 
2011782736:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
Internal Error</pre>

(我对linux shell不熟悉，只能借助网络依样画葫芦)

**Comment by 185264646** [comment]
> > > 最近玩小米AX3600路由器，破解SSH后，使用此登录程序（v2.1）报错，调试信息为：
> > > ```
> > >   ++ openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf -
> > > ```
> > 
> > 
> > 能否尝试一下将这一行修改为`openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf /dev/stdin`之后，能否在旧版本openssl下工作呢？
> > > ```
> > >   Error loading config file '-'
> > > ```
> 
> 这个改动，在 openssl v1.1.1 里就不能成功。出错提示：
> 
> Can't open /dev/stdin for reading, No such file or directory
> 2011782736:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/dev/stdin','r') 

这实在是超出我的认知范畴了。你的路由器上的linux系统似乎连`/dev/stdin`这个软连接都不提供。我目前完全没有见过类似情况。正常情况下linux都会提供这个软连接指向标准输入设备。哪怕是我手头的安卓手机和windows上的msys2也都支持。

你可以尝试把`ls /dev`的结果贴出来，我确认一下是否真的不存在/dev/stdout,stdin,stderr等设备文件。

> 2011782736:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
> Internal Error
> 
> (我对linux shell不熟悉，只能借助网络依样画葫芦)

**Comment by wang20150419** [comment]
> > > > 最近玩小米AX3600路由器，破解SSH后，使用此登录程序（v2.1）报错，调试信息为：
> > > > ```
> > > >   ++ openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf -
> > > > ```
> > > 
> > > 
> > > 能否尝试一下将这一行修改为`openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf /dev/stdin`之后，能否在旧版本openssl下工作呢？
> > > > ```
> > > >   Error loading config file '-'
> > > > ```
> > 
> > 
> > 这个改动，在 openssl v1.1.1 里就不能成功。出错提示：
> > Can't open /dev/stdin for reading, No such file or directory
> > 2011782736:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/dev/stdin','r')
> 
> 这实在是超出我的认知范畴了。你的路由器上的linux系统似乎连`/dev/stdin`这个软连接都不提供。我目前完全没有见过类似情况。正常情况下linux都会提供这个软连接指向标准输入设备。哪怕是我手头的安卓手机和windows上的msys2也都支持。
> 
> 你可以尝试把`ls /dev`的结果贴出来，我确认一下是否真的不存在/dev/stdout,stdin,stderr等设备文件。
> 
> > 2011782736:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
> > Internal Error
> > (我对linux shell不熟悉，只能借助网络依样画葫芦)

linux 系统，是有你说的 stdin,stdout的。
小米系列路由器，用的是  openwrt 系统，的确在 /dev 里，没有 stdin, stdout, stderr 这样的设备。查了一下华硕的路由器，也是没有。
见附图。
![2024-02-20_19-04-42](https://github.com/185264646/HUST-login/assets/12016822/320129ad-1090-4e12-8a11-c4c7b3b58b01)

**Comment by 185264646** [comment]
> > > > > 最近玩小米AX3600路由器，破解SSH后，使用此登录程序（v2.1）报错，调试信息为：
> > > > > ```
> > > > >   ++ openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf -
> > > > > ```
> > > > 
> > > > 
> > > > 能否尝试一下将这一行修改为`openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf /dev/stdin`之后，能否在旧版本openssl下工作呢？
> > > > > ```
> > > > >   Error loading config file '-'
> > > > > ```
> > > 
> > > 
> > > 这个改动，在 openssl v1.1.1 里就不能成功。出错提示：
> > > Can't open /dev/stdin for reading, No such file or directory
> > > 2011782736:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/dev/stdin','r')
> > 
> > 
> > 这实在是超出我的认知范畴了。你的路由器上的linux系统似乎连`/dev/stdin`这个软连接都不提供。我目前完全没有见过类似情况。正常情况下linux都会提供这个软连接指向标准输入设备。哪怕是我手头的安卓手机和windows上的msys2也都支持。
> > 你可以尝试把`ls /dev`的结果贴出来，我确认一下是否真的不存在/dev/stdout,stdin,stderr等设备文件。
> > > 2011782736:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
> > > Internal Error
> > > (我对linux shell不熟悉，只能借助网络依样画葫芦)
> 
> linux 系统，是有你说的 stdin,stdout的。 小米系列路由器，用的是 openwrt 系统，的确在 /dev 里，没有 stdin, stdout, stderr 这样的设备。查了一下华硕的路由器，也是没有。 见附图。 ![2024-02-20_19-04-42](https://private-user-images.githubusercontent.com/12016822/306237720-320129ad-1090-4e12-8a11-c4c7b3b58b01.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjgwODcsIm5iZiI6MTcwODQyNzc4NywicGF0aCI6Ii8xMjAxNjgyMi8zMDYyMzc3MjAtMzIwMTI5YWQtMTA5MC00ZTEyLThhMTEtYzRjN2IzYjU4YjAxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDExMTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMWMxYzBmMWQ0ZGNlNDQ2NzJlMDlmNmRjMjgxYWFmMDA3ZGQyZmE2ZjZjMDhiNTQzZTI5MDdmYzI3YTNkYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Gz2RMtdiEKOr1CscTY569Y-OrphkkjKuyFuSdvZOP4)

openwrt也是linux的一种，所以按道理不应该有这种问题。

linux系统上是应该存在 /dev/stdin->/proc/self/fd/0->/dev/pts/0 这样一个软连接链的。这些设备上存在/proc/self/fd/0吗？如果存在的话，试试把/dev/stdin修改为/proc/self/fd/0再试一次呢？如果能解决问题的话，我建议的解决方法是添加开机脚本`ln -s /proc/self/fd/0 /dev/stdin`，因为这个软连接在很多系统上都提供。

**Comment by 185264646** [comment]
> > > > > 最近玩小米AX3600路由器，破解SSH后，使用此登录程序（v2.1）报错，调试信息为：
> > > > > ```
> > > > >   ++ openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf -
> > > > > ```
> > > > 
> > > > 
> > > > 能否尝试一下将这一行修改为`openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf /dev/stdin`之后，能否在旧版本openssl下工作呢？
> > > > > ```
> > > > >   Error loading config file '-'
> > > > > ```
> > > 
> > > 
> > > 这个改动，在 openssl v1.1.1 里就不能成功。出错提示：
> > > Can't open /dev/stdin for reading, No such file or directory
> > > 2011782736:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/dev/stdin','r')
> > 
> > 
> > 这实在是超出我的认知范畴了。你的路由器上的linux系统似乎连`/dev/stdin`这个软连接都不提供。我目前完全没有见过类似情况。正常情况下linux都会提供这个软连接指向标准输入设备。哪怕是我手头的安卓手机和windows上的msys2也都支持。
> > 你可以尝试把`ls /dev`的结果贴出来，我确认一下是否真的不存在/dev/stdout,stdin,stderr等设备文件。
> > > 2011782736:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
> > > Internal Error
> > > (我对linux shell不熟悉，只能借助网络依样画葫芦)
> 
> linux 系统，是有你说的 stdin,stdout的。 小米系列路由器，用的是 openwrt 系统，的确在 /dev 里，没有 stdin, stdout, stderr 这样的设备。查了一下华硕的路由器，也是没有。 见附图。 ![2024-02-20_19-04-42](https://private-user-images.githubusercontent.com/12016822/306237720-320129ad-1090-4e12-8a11-c4c7b3b58b01.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjgwODcsIm5iZiI6MTcwODQyNzc4NywicGF0aCI6Ii8xMjAxNjgyMi8zMDYyMzc3MjAtMzIwMTI5YWQtMTA5MC00ZTEyLThhMTEtYzRjN2IzYjU4YjAxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDExMTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMWMxYzBmMWQ0ZGNlNDQ2NzJlMDlmNmRjMjgxYWFmMDA3ZGQyZmE2ZjZjMDhiNTQzZTI5MDdmYzI3YTNkYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Gz2RMtdiEKOr1CscTY569Y-OrphkkjKuyFuSdvZOP4)

我刚才在虚拟机里测试了最新的openwrt，也是存在/dev/stdin, /dev/stdout 和 /dev/stderr这些设备文件的。所以可能是这些定制系统的缘故。

![图片](https://github.com/185264646/HUST-login/assets/43387518/cda12792-64e9-4401-9ab2-37aebb3a6fa5)

**Comment by wang20150419** [comment]
> > > > > > 最近玩小米AX3600路由器，破解SSH后，使用此登录程序（v2.1）报错，调试信息为：
> > > > > > ```
> > > > > >   ++ openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf -
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 能否尝试一下将这一行修改为`openssl asn1parse -out /tmp/tmp.HhMGoC -noout -genconf /dev/stdin`之后，能否在旧版本openssl下工作呢？
> > > > > > ```
> > > > > >   Error loading config file '-'
> > > > > > ```
> > > > 
> > > > 
> > > > 这个改动，在 openssl v1.1.1 里就不能成功。出错提示：
> > > > Can't open /dev/stdin for reading, No such file or directory
> > > > 2011782736:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/dev/stdin','r')
> > > 
> > > 
> > > 这实在是超出我的认知范畴了。你的路由器上的linux系统似乎连`/dev/stdin`这个软连接都不提供。我目前完全没有见过类似情况。正常情况下linux都会提供这个软连接指向标准输入设备。哪怕是我手头的安卓手机和windows上的msys2也都支持。
> > > 你可以尝试把`ls /dev`的结果贴出来，我确认一下是否真的不存在/dev/stdout,stdin,stderr等设备文件。
> > > > 2011782736:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
> > > > Internal Error
> > > > (我对linux shell不熟悉，只能借助网络依样画葫芦)
> > 
> > 
> > linux 系统，是有你说的 stdin,stdout的。 小米系列路由器，用的是 openwrt 系统，的确在 /dev 里，没有 stdin, stdout, stderr 这样的设备。查了一下华硕的路由器，也是没有。 见附图。 ![2024-02-20_19-04-42](https://private-user-images.githubusercontent.com/12016822/306237720-320129ad-1090-4e12-8a11-c4c7b3b58b01.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjgwODcsIm5iZiI6MTcwODQyNzc4NywicGF0aCI6Ii8xMjAxNjgyMi8zMDYyMzc3MjAtMzIwMTI5YWQtMTA5MC00ZTEyLThhMTEtYzRjN2IzYjU4YjAxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDExMTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMWMxYzBmMWQ0ZGNlNDQ2NzJlMDlmNmRjMjgxYWFmMDA3ZGQyZmE2ZjZjMDhiNTQzZTI5MDdmYzI3YTNkYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Gz2RMtdiEKOr1CscTY569Y-OrphkkjKuyFuSdvZOP4)
> 
> 我刚才在虚拟机里测试了最新的openwrt，也是存在/dev/stdin, /dev/stdout 和 /dev/stderr这些设备文件的。所以可能是这些定制系统的缘故。
> 
> ![图片](https://private-user-images.githubusercontent.com/43387518/306243336-cda12792-64e9-4401-9ab2-37aebb3a6fa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NDMwNDAsIm5iZiI6MTcwODQ0Mjc0MCwicGF0aCI6Ii80MzM4NzUxOC8zMDYyNDMzMzYtY2RhMTI3OTItNjRlOS00NDAxLTlhYjItMzdhZWJiM2E2ZmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE1MjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMjI3MjAzNTgzODRmNWMxMDc5MWIwODg2ZWZhZWY2M2ZkZTFmOGRkOGQzMGUyZjE5YzZhNTNkMDc2YzUyMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vJNWcyzO_1lx1jEaUsFy6yJPRl3KE5KmSZwNgZqVhoE)

 openwrt 低版本里，有 /proc/self/fd/0->/dev/pts/0 这样的软连接，使用 /proc/self/fd/0 作为 stdin，成功登录，问题解决。
openwrt 21.0 里，也没有 stdin， stdout， 但在最新的 22.0 里，有。
小米路由器系列，是在 openwrt 18.06 的基础上魔改的。
